In [10]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    "2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Read and display each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    print(f"Reading and displaying contents of {file_name}")
    df = pd.read_csv(file_url)
    display(df)  # This will display the DataFrame in a nice format

Reading and displaying contents of 1597139_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/4/multikills/0/id,players/4/multikills/0/numberOfKills,players/4/multikills/0/count,players/4/multikills/1/id,players/4/multikills/1/numberOfKills,players/4/multikills/1/count,players/0/objectives/2/id,players/0/objectives/2/statePath/0/id,players/0/objectives/2/type,players/0/objectives/2/completionCount
0,155,155,Aster,1,False,71,178,80,killAssistsReceivedFromPlayer-76561198216422051,76561198216422051,...,multikill-2,2,3,multikill-3,3.0,2.0,NaN,NaN,NaN,NaN
1,184,184,Team Spirit,1,False,66,150,36,killAssistsReceivedFromPlayer-76561198143644474,76561198143644474,...,multikill-2,2,1,NaN,NaN,NaN,destroyTower,destroyTower,destroyTower,1.0

Reading and displaying contents of 1598060_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/0/objectives/3/statePath/0/id,players/0/objectives/3/type,players/0/objectives/3/completionCount,players/0/objectives/4/id,players/0/objectives/4/statePath/0/id,players/0/objectives/4/type,players/0/objectives/4/completionCount,players/0/multikills/0/id,players/0/multikills/0/numberOfKills,players/0/multikills/0/count
0,309,309,PSG.LGD,2,False,101,262,91,killAssistsReceivedFromPlayer-76561198262479756,76561198262479756,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,184,184,Team Spirit,1,False,86,211,60,killAssistsReceivedFromPlayer-76561198859019881,76561198859019881,...,destroyBarracksMelee,destroyBarracksMelee,3.0,destroyBarracksRange,destroyBarracksRange,destroyBarracksRange,3.0,multikill-2,2.0,3.0

Reading and displaying contents of 1614507_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/4/objectives/1/type,players/4/objectives/1/completionCount,players/3/objectives/2/id,players/3/objectives/2/statePath/0/id,players/3/objectives/2/type,players/3/objectives/2/completionCount,players/3/objectives/3/id,players/3/objectives/3/statePath/0/id,players/3/objectives/3/type,players/3/objectives/3/completionCount
0,155,155,Aster,1,False,103,239,130,killAssistsReceivedFromPlayer-76561198108481367,76561198108481367,...,slayRoshan,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,449,449,OG,1,False,64,142,65,killAssistsReceivedFromPlayer-76561198128242457,76561198128242457,...,destroyTower,1,slayRoshan,slayRoshan,slayRoshan,2.0,destroyBarracksRange,destroyBarracksRange,destroyBarracksRange,1.0

Reading and displaying contents of 2432453_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,multikills/1/id,multikills/1/numberOfKills,multikills/1/count,players/3/multikills/1/id,players/3/multikills/1/numberOfKills,players/3/multikills/1/count,players/4/objectives/2/id,players/4/objectives/2/statePath/0/id,players/4/objectives/2/type,players/4/objectives/2/completionCount
0,450,450,Secret,2,False,105,273,103,killAssistsReceivedFromPlayer-76561197970632344,76561197970632344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1546,1546,Tundra Esports,0,False,55,112,41,killAssistsReceivedFromPlayer-76561198047544485,76561198047544485,...,multikill-3,3.0,3.0,multikill-3,3.0,3.0,destroyTower,destroyTower,destroyTower,3.0

Reading and displaying contents of 2432302_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/3/objectives/2/id,players/3/objectives/2/statePath/0/id,players/3/objectives/2/type,players/3/objectives/2/completionCount,players/3/multikills/0/id,players/3/multikills/0/numberOfKills,players/3/multikills/0/count,players/3/multikills/1/id,players/3/multikills/1/numberOfKills,players/3/multikills/1/count
0,450,450,Secret,1,False,72,155,56,killAssistsReceivedFromPlayer-76561198033828054,76561198033828054,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,83,83,Team Liquid,1,False,77,186,81,killAssistsReceivedFromPlayer-76561198087883707,76561198087883707,...,destroyTower,destroyTower,destroyTower,5.0,multikill-2,2.0,4.0,multikill-3,3.0,2.0

Reading and displaying contents of 2579089_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/4/weaponKills/xm1014,players/4/weaponKills/hegrenade,players/4/objectives/2/id,players/4/objectives/2/statePath/0/id,players/4/objectives/2/type,players/4/objectives/2/completionCount,players/4/objectives/3/id,players/4/objectives/3/statePath/0/id,players/4/objectives/3/type,players/4/objectives/3/completionCount
0,3128,3128,ECSTATIC,0,False,167,38,38,killAssistsReceivedFromPlayer-76561198070876270,76561198070876270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47336,47336,forZe,1,False,213,42,42,killAssistsReceivedFromPlayer-76561198026088156,76561198026088156,...,1.0,1.0,beginDefuseWithKit,beginDefuseWithKit,beginDefuseWithKit,2.0,defuseBomb,defuseBomb,defuseBomb,2.0

Reading and displaying contents of 2578928_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/3/killAssistsReceivedFromPlayer/3/id,players/3/killAssistsReceivedFromPlayer/3/playerId,players/3/killAssistsReceivedFromPlayer/3/killAssistsReceived,players/3/weaponKills/molotov,players/3/weaponKills/mp9,players/3/weaponKills/galilar,players/3/weaponKills/glock,players/4/weaponKills/deagle,players/4/weaponKills/usp_silencer,players/4/weaponKills/mp9
0,47336,47336,forZe,0,False,165,35,35,killAssistsReceivedFromPlayer-76561198350362302,76561198350362302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3128,3128,ECSTATIC,1,False,193,29,29,killAssistsReceivedFromPlayer-76561198070876270,76561198070876270,...,killAssistsReceivedFromPlayer-76561198102263776,7.656120e+16,1.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0

Reading and displaying contents of 2579048_state.csv

,id,statePath/0/id,name,score,won,kills,killAssistsReceived,killAssistsGiven,killAssistsReceivedFromPlayer/0/id,killAssistsReceivedFromPlayer/0/playerId,...,players/3/objectives/1/type,players/3/objectives/1/completionCount,players/3/objectives/2/id,players/3/objectives/2/statePath/0/id,players/3/objectives/2/type,players/3/objectives/2/completionCount,players/4/weaponKills/p250,players/4/weaponKills/deagle,players/4/weaponKills/mp9,players/4/weaponKills/fiveseven
0,47336,47336,forZe,1,False,221,32,32,killAssistsReceivedFromPlayer-76561198026088156,76561198026088156,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,927,927,9INE,0,False,188,38,38,killAssistsReceivedFromPlayer-76561197985246786,76561197985246786,...,plantBomb,3.0,explodeBomb,explodeBomb,explodeBomb,3.0,2.0,1.0,1.0,1.0

In [11]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    ##"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "won", "kills", "killAssistsReceived", "killAssistsGiven"]

# Read and display selected columns for each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    print(f"Reading and displaying selected columns of {file_name}")
    df = pd.read_csv(file_url, usecols=columns_to_select)
    display(df)  # This will display the selected columns of the DataFrame in a nice format

Reading and displaying selected columns of 1597139_state.csv

          name  score    won  kills  killAssistsReceived  killAssistsGiven
0        Aster      1  False     71                  178                80
1  Team Spirit      1  False     66                  150                36

Reading and displaying selected columns of 1598060_state.csv

          name  score    won  kills  killAssistsReceived  killAssistsGiven
0      PSG.LGD      2  False    101                  262                91
1  Team Spirit      1  False     86                  211                60

Reading and displaying selected columns of 1614507_state.csv

    name  score    won  kills  killAssistsReceived  killAssistsGiven
0  Aster      1  False    103                  239               130
1     OG      1  False     64                  142                65

Reading and displaying selected columns of 2432453_state.csv

             name  score    won  kills  killAssistsReceived  killAssistsGiven
0          Secret      2  False    105                  273               103
1  Tundra Esports      0  False     55                  112                41

Reading and displaying selected columns of 2432302_state.csv

          name  score    won  kills  killAssistsReceived  killAssistsGiven
0       Secret      1  False     72                  155                56
1  Team Liquid      1  False     77                  186                81

Reading and displaying selected columns of 2579089_state.csv

       name  score    won  kills  killAssistsReceived  killAssistsGiven
0  ECSTATIC      0  False    167                   38                38
1     forZe      1  False    213                   42                42

Reading and displaying selected columns of 2578928_state.csv

       name  score    won  kills  killAssistsReceived  killAssistsGiven
0     forZe      0  False    165                   35                35
1  ECSTATIC      1  False    193                   29                29

Reading and displaying selected columns of 2579048_state.csv

    name  score    won  kills  killAssistsReceived  killAssistsGiven
0  forZe      1  False    221                   32                32
1   9INE      0  False    188                   38                38

In [ ]:
# average score, average kills, and average kill assists

In [13]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "kills", "killAssistsReceived", "killAssistsGiven"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_score": 0,
                "total_kills": 0,
                "total_kill_assists_received": 0,
                "total_kill_assists_given": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        team_statistics[team_name]["total_score"] += row["score"]
        team_statistics[team_name]["total_kills"] += row["kills"]
        team_statistics[team_name]["total_kill_assists_received"] += row["killAssistsReceived"]
        team_statistics[team_name]["total_kill_assists_given"] += row["killAssistsGiven"]

# Calculate average statistics and print the results
print("Team Statistics:")
for team_name, stats in team_statistics.items():
    avg_score = stats["total_score"] / stats["total_matches"]
    avg_kills = stats["total_kills"] / stats["total_matches"]
    avg_kill_assists_received = stats["total_kill_assists_received"] / stats["total_matches"]
    avg_kill_assists_given = stats["total_kill_assists_given"] / stats["total_matches"]
    
    print(f"Team: {team_name}")
    print(f"Average Score: {avg_score:.2f}")
    print(f"Average Kills: {avg_kills:.2f}")
    print(f"Average Kill Assists Received: {avg_kill_assists_received:.2f}")
    print(f"Average Kill Assists Given: {avg_kill_assists_given:.2f}")
    print()

Team Statistics:
Team: Aster
Average Score: 1.00
Average Kills: 87.00
Average Kill Assists Received: 208.50
Average Kill Assists Given: 105.00

Team: Team Spirit
Average Score: 1.00
Average Kills: 76.00
Average Kill Assists Received: 180.50
Average Kill Assists Given: 48.00

Team: PSG.LGD
Average Score: 2.00
Average Kills: 101.00
Average Kill Assists Received: 262.00
Average Kill Assists Given: 91.00

Team: OG
Average Score: 1.00
Average Kills: 64.00
Average Kill Assists Received: 142.00
Average Kill Assists Given: 65.00

Team: Secret
Average Score: 1.50
Average Kills: 88.50
Average Kill Assists Received: 214.00
Average Kill Assists Given: 79.50

Team: Tundra Esports
Average Score: 0.00
Average Kills: 55.00
Average Kill Assists Received: 112.00
Average Kill Assists Given: 41.00

Team: Team Liquid
Average Score: 1.00
Average Kills: 77.00
Average Kill Assists Received: 186.00
Average Kill Assists Given: 81.00

Team: ECSTATIC
Average Score: 0.50
Average Kills: 180.00
Average Kill Assists Received: 33.50
Average Kill Assists Given: 33.50

Team: forZe
Average Score: 0.67
Average Kills: 199.67
Average Kill Assists Received: 36.33
Average Kill Assists Given: 36.33

Team: 9INE
Average Score: 0.00
Average Kills: 188.00
Average Kill Assists Received: 38.00
Average Kill Assists Given: 38.00

In [ ]:
# Analyzing Wins and Losses

In [15]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "kills", "killAssistsReceived", "killAssistsGiven", "won"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_score": 0,
                "total_kills": 0,
                "total_kill_assists_received": 0,
                "total_kill_assists_given": 0,
                "total_wins": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        team_statistics[team_name]["total_score"] += row["score"]
        team_statistics[team_name]["total_kills"] += row["kills"]
        team_statistics[team_name]["total_kill_assists_received"] += row["killAssistsReceived"]
        team_statistics[team_name]["total_kill_assists_given"] += row["killAssistsGiven"]
        if row["won"]:
            team_statistics[team_name]["total_wins"] += 1

# Analyze wins and losses and print the results
print("Wins and Losses Analysis:")
for team_name, stats in team_statistics.items():
    total_matches = stats["total_matches"]
    total_wins = stats["total_wins"]
    win_percentage = (total_wins / total_matches) * 100 if total_matches > 0 else 0
    
    avg_score = stats["total_score"] / total_matches
    avg_kills = stats["total_kills"] / total_matches
    avg_kill_assists_received = stats["total_kill_assists_received"] / total_matches
    avg_kill_assists_given = stats["total_kill_assists_given"] / total_matches
    
    print(f"Team: {team_name}")
    print(f"Win Percentage: {win_percentage:.2f}%")
    print(f"Average Score: {avg_score:.2f}")
    print(f"Average Kills: {avg_kills:.2f}")
    print(f"Average Kill Assists Received: {avg_kill_assists_received:.2f}")
    print(f"Average Kill Assists Given: {avg_kill_assists_given:.2f}")
    print()

Wins and Losses Analysis:
Team: Aster
Win Percentage: 0.00%
Average Score: 1.00
Average Kills: 87.00
Average Kill Assists Received: 208.50
Average Kill Assists Given: 105.00

Team: Team Spirit
Win Percentage: 0.00%
Average Score: 1.00
Average Kills: 76.00
Average Kill Assists Received: 180.50
Average Kill Assists Given: 48.00

Team: PSG.LGD
Win Percentage: 0.00%
Average Score: 2.00
Average Kills: 101.00
Average Kill Assists Received: 262.00
Average Kill Assists Given: 91.00

Team: OG
Win Percentage: 0.00%
Average Score: 1.00
Average Kills: 64.00
Average Kill Assists Received: 142.00
Average Kill Assists Given: 65.00

Team: Secret
Win Percentage: 0.00%
Average Score: 1.50
Average Kills: 88.50
Average Kill Assists Received: 214.00
Average Kill Assists Given: 79.50

Team: Tundra Esports
Win Percentage: 0.00%
Average Score: 0.00
Average Kills: 55.00
Average Kill Assists Received: 112.00
Average Kill Assists Given: 41.00

Team: Team Liquid
Win Percentage: 0.00%
Average Score: 1.00
Average Kills: 77.00
Average Kill Assists Received: 186.00
Average Kill Assists Given: 81.00

Team: ECSTATIC
Win Percentage: 0.00%
Average Score: 0.50
Average Kills: 180.00
Average Kill Assists Received: 33.50
Average Kill Assists Given: 33.50

Team: forZe
Win Percentage: 0.00%
Average Score: 0.67
Average Kills: 199.67
Average Kill Assists Received: 36.33
Average Kill Assists Given: 36.33

Team: 9INE
Win Percentage: 0.00%
Average Score: 0.00
Average Kills: 188.00
Average Kill Assists Received: 38.00
Average Kill Assists Given: 38.00

In [ ]:
# Identify Top Performers

In [17]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "kills", "killAssistsReceived", "killAssistsGiven", "won"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_score": 0,
                "total_kills": 0,
                "total_kill_assists_received": 0,
                "total_kill_assists_given": 0,
                "total_wins": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        team_statistics[team_name]["total_score"] += row["score"]
        team_statistics[team_name]["total_kills"] += row["kills"]
        team_statistics[team_name]["total_kill_assists_received"] += row["killAssistsReceived"]
        team_statistics[team_name]["total_kill_assists_given"] += row["killAssistsGiven"]
        if row["won"]:
            team_statistics[team_name]["total_wins"] += 1

# Identify top performers and print the results
print("Top Performers:")
top_performers = {
    "score": [],
    "kills": [],
    "kill_assists_received": [],
    "kill_assists_given": []
}

for team_name, stats in team_statistics.items():
    total_matches = stats["total_matches"]
    if total_matches > 0:
        avg_score = stats["total_score"] / total_matches
        avg_kills = stats["total_kills"] / total_matches
        avg_kill_assists_received = stats["total_kill_assists_received"] / total_matches
        avg_kill_assists_given = stats["total_kill_assists_given"] / total_matches
        
        top_performers["score"].append((team_name, avg_score))
        top_performers["kills"].append((team_name, avg_kills))
        top_performers["kill_assists_received"].append((team_name, avg_kill_assists_received))
        top_performers["kill_assists_given"].append((team_name, avg_kill_assists_given))

# Function to print top performers for a given metric
def print_top_performers(metric_name, metric_list):
    sorted_list = sorted(metric_list, key=lambda x: x[1], reverse=True)
    print(f"Top Performers for {metric_name}:")
    for idx, (team_name, value) in enumerate(sorted_list):
        print(f"{idx + 1}. {team_name}: {value:.2f}")

print_top_performers("Score", top_performers["score"])
print_top_performers("Kills", top_performers["kills"])
print_top_performers("Kill Assists Received", top_performers["kill_assists_received"])
print_top_performers("Kill Assists Given", top_performers["kill_assists_given"])

Top Performers:
Top Performers for Score:
1. PSG.LGD: 2.00
2. Secret: 1.50
3. Aster: 1.00
4. Team Spirit: 1.00
5. OG: 1.00
6. Team Liquid: 1.00
7. forZe: 0.67
8. ECSTATIC: 0.50
9. Tundra Esports: 0.00
10. 9INE: 0.00
Top Performers for Kills:
1. forZe: 199.67
2. 9INE: 188.00
3. ECSTATIC: 180.00
4. PSG.LGD: 101.00
5. Secret: 88.50
6. Aster: 87.00
7. Team Liquid: 77.00
8. Team Spirit: 76.00
9. OG: 64.00
10. Tundra Esports: 55.00
Top Performers for Kill Assists Received:
1. PSG.LGD: 262.00
2. Secret: 214.00
3. Aster: 208.50
4. Team Liquid: 186.00
5. Team Spirit: 180.50
6. OG: 142.00
7. Tundra Esports: 112.00
8. 9INE: 38.00
9. forZe: 36.33
10. ECSTATIC: 33.50
Top Performers for Kill Assists Given:
1. Aster: 105.00
2. PSG.LGD: 91.00
3. Team Liquid: 81.00
4. Secret: 79.50
5. OG: 65.00
6. Team Spirit: 48.00
7. Tundra Esports: 41.00
8. 9INE: 38.00
9. forZe: 36.33
10. ECSTATIC: 33.50

In [ ]:
# Visualize Performance

In [ ]:
# Correlation Analysis

In [18]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "kills", "killAssistsReceived", "killAssistsGiven", "won"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_score": 0,
                "total_kills": 0,
                "total_kill_assists_received": 0,
                "total_kill_assists_given": 0,
                "total_wins": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        team_statistics[team_name]["total_score"] += row["score"]
        team_statistics[team_name]["total_kills"] += row["kills"]
        team_statistics[team_name]["total_kill_assists_received"] += row["killAssistsReceived"]
        team_statistics[team_name]["total_kill_assists_given"] += row["killAssistsGiven"]
        if row["won"]:
            team_statistics[team_name]["total_wins"] += 1

# Create a DataFrame with relevant data
data = {
    "score": [stats["total_score"] / stats["total_matches"] for stats in team_statistics.values()],
    "kills": [stats["total_kills"] / stats["total_matches"] for stats in team_statistics.values()],
    "kill_assists_received": [stats["total_kill_assists_received"] / stats["total_matches"] for stats in team_statistics.values()],
    "kill_assists_given": [stats["total_kill_assists_given"] / stats["total_matches"] for stats in team_statistics.values()]
}
df = pd.DataFrame(data, index=team_statistics.keys())

# Calculate correlations
correlation_matrix = df.corr()

# Print the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
                          score     kills  kill_assists_received  \
score                  1.000000 -0.343562               0.819927
kills                 -0.343562  1.000000              -0.737317
kill_assists_received  0.819927 -0.737317               1.000000
kill_assists_given     0.730853 -0.537384               0.868246

                       kill_assists_given
score                            0.730853
kills                           -0.537384
kill_assists_received            0.868246
kill_assists_given               1.000000

In [ ]:
# Identifying Patterns

In [19]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "score", "kills", "killAssistsReceived", "killAssistsGiven", "won"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_score": 0,
                "total_kills": 0,
                "total_kill_assists_received": 0,
                "total_kill_assists_given": 0,
                "total_wins": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        team_statistics[team_name]["total_score"] += row["score"]
        team_statistics[team_name]["total_kills"] += row["kills"]
        team_statistics[team_name]["total_kill_assists_received"] += row["killAssistsReceived"]
        team_statistics[team_name]["total_kill_assists_given"] += row["killAssistsGiven"]
        if row["won"]:
            team_statistics[team_name]["total_wins"] += 1

# Create a DataFrame with relevant data
data = {
    "score": [stats["total_score"] / stats["total_matches"] for stats in team_statistics.values()],
    "kills": [stats["total_kills"] / stats["total_matches"] for stats in team_statistics.values()],
    "kill_assists_received": [stats["total_kill_assists_received"] / stats["total_matches"] for stats in team_statistics.values()],
    "kill_assists_given": [stats["total_kill_assists_given"] / stats["total_matches"] for stats in team_statistics.values()]
}
df = pd.DataFrame(data, index=team_statistics.keys())

# Calculate correlations
correlation_matrix = df.corr()

# Identify patterns in the correlation matrix
print("Patterns in the Correlation Matrix:")
for col1 in correlation_matrix.columns:
    for col2 in correlation_matrix.columns:
        if col1 != col2:
            correlation_value = correlation_matrix.loc[col1, col2]
            if correlation_value > 0.5 or correlation_value < -0.5:
                print(f"{col1} and {col2} have a correlation of {correlation_value:.2f}")

Patterns in the Correlation Matrix:
score and kill_assists_received have a correlation of 0.82
score and kill_assists_given have a correlation of 0.73
kills and kill_assists_received have a correlation of -0.74
kills and kill_assists_given have a correlation of -0.54
kill_assists_received and score have a correlation of 0.82
kill_assists_received and kills have a correlation of -0.74
kill_assists_received and kill_assists_given have a correlation of 0.87
kill_assists_given and score have a correlation of 0.73
kill_assists_given and kills have a correlation of -0.54
kill_assists_given and kill_assists_received have a correlation of 0.87

In [ ]:
# Comparative Analysis

In [22]:
import pandas as pd

# Base URL for the GitHub repository
base_url = "https://github.com/KamoEllen/GRID-Esports-DataJam-23/raw/main/"

# List of file names
file_names = [
    "1597139_state.csv",
    "1598060_state.csv",
    "1614507_state.csv",
    "2432453_state.csv",
    "2432302_state.csv",
    #"2364966_state.csv",
    "2579089_state.csv",
    "2578928_state.csv",
    "2579048_state.csv"
]

# Columns to select
columns_to_select = ["name", "won"]

# Dictionary to store team statistics
team_statistics = {}

# Read and process each CSV file
for file_name in file_names:
    file_url = base_url + file_name
    df = pd.read_csv(file_url, usecols=columns_to_select)
    
    for index, row in df.iterrows():
        team_name = row["name"]
        if team_name not in team_statistics:
            team_statistics[team_name] = {
                "total_matches": 0,
                "total_wins": 0
            }
        team_statistics[team_name]["total_matches"] += 1
        if row["won"]:
            team_statistics[team_name]["total_wins"] += 1

# Calculate win-loss ratio for each team
win_loss_ratios = {}
for team_name, stats in team_statistics.items():
    total_wins = stats["total_wins"]
    total_matches = stats["total_matches"]
    if total_matches > 0:
        win_loss_ratio = total_wins / total_matches
        win_loss_ratios[team_name] = win_loss_ratio

# Sort teams based on win-loss ratio and print the results
sorted_teams = sorted(win_loss_ratios.items(), key=lambda x: x[1], reverse=True)
print("Win-Loss Ratios:")
for idx, (team_name, ratio) in enumerate(sorted_teams):
    print(f"{idx + 1}. {team_name}: Win-Loss Ratio = {ratio:.2f}")

Win-Loss Ratios:
1. Aster: Win-Loss Ratio = 0.00
2. Team Spirit: Win-Loss Ratio = 0.00
3. PSG.LGD: Win-Loss Ratio = 0.00
4. OG: Win-Loss Ratio = 0.00
5. Secret: Win-Loss Ratio = 0.00
6. Tundra Esports: Win-Loss Ratio = 0.00
7. Team Liquid: Win-Loss Ratio = 0.00
8. ECSTATIC: Win-Loss Ratio = 0.00
9. forZe: Win-Loss Ratio = 0.00
10. 9INE: Win-Loss Ratio = 0.00